// Google sheet npm package
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

// File handling package
import fs from "fs";

// spreadsheet key is the long id in the sheets URL
const RESPONSES_SHEET_ID = "1W1A87swNCtM9O8yIioWLQAOa_Vdl7XxuhSou_Pgh81g";

// Credentials for the service account
const CREDENTIALS = JSON.parse(
  fs.readFileSync("mystic-berm-404114-f27cc40b5a1c.json")
);

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL || CREDENTIALS.client_email,
  key: process.env.GOOGLE_PRIVATE_KEY || CREDENTIALS.private_key,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

// Create a new document
const doc = new GoogleSpreadsheet(RESPONSES_SHEET_ID, serviceAccountAuth);

export const getGoogleSheetData = async function (req, res) {
  await doc.loadInfo();
  let sheet = doc.sheetsByIndex[0];

  const rowsValues = await sheet.getRows();

  const values = rowsValues.map((item) => {
    return { email: item._rawData[0], user_name: item._rawData[1] };
  });
  console.log(values);
  res.status(200).send(values);
};

export const addGoogleSheetData = async function (req, res) {
  // let data = {
  //   user_name: "Sergey Brin",
  //   email: "sergey@google.com",
  //   password: "Sergey123",
  // };

  const { user_name, email, password } = req.body;

  await doc.loadInfo();
  let sheet = doc.sheetsByIndex[0];

  await sheet.setHeaderRow(["email", "user_name", "password"]);

  await sheet.addRow({ user_name, email, password });

  res.status(200).send("data added sucessfully");
};

export const updateGoogleSheetData = async function (req, res) {
  const { keyval, oldData, newData } = req.body;

  await doc.loadInfo();

  // Index of the sheet
  let sheet = doc.sheetsByIndex[0];

  let rows = await sheet.getRows();

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    if (row[keyval] === oldValue) {
      rows[index] = newValue;
      await rows[index].save();
      break;
    }
  }
};

export const deleteGoogleSheetData = async function (req, res) {
  const { key, value } = req.body;

  await doc.loadInfo();

  // Index of the sheet
  let sheet = doc.sheetsByIndex[0];

  let rows = await sheet.getRows();

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    if (row[key] === value) {
      await rows[index].delete();
      break;
    }
  }
};

const getRow = async (email) => {
  // use service account creds
  await doc.useServiceAccountAuth({
    client_email: CREDENTIALS.client_email,
    private_key: CREDENTIALS.private_key,
  });

  // load the documents info
  await doc.loadInfo();

  // Index of the sheet
  let sheet = doc.sheetsByIndex[0];

  // Get all the rows
  let rows = await sheet.getRows();

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    if (row.email == email) {
      console.log(row.user_name);
      console.log(row.password);
    }
  }
};

// getRow('email@gmail.com');

const addRow = async (rows) => {
  // use service account creds
  await doc.useServiceAccountAuth({
    client_email: CREDENTIALS.client_email,
    private_key: CREDENTIALS.private_key,
  });

  await doc.loadInfo();

  // Index of the sheet
  let sheet = doc.sheetsByIndex[0];

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    await sheet.addRow(row);
  }
};

let rows = [
  {
    email: "email@email.com",
    user_name: "ramesh",
    password: "abcd@1234",
  },
  {
    email: "email@gmail.com",
    user_name: "dilip",
    password: "abcd@1234",
  },
];

// addRow(rows);

const updateRow = async (keyValue, oldValue, newValue) => {
  // use service account creds
  await doc.useServiceAccountAuth({
    client_email: CREDENTIALS.client_email,
    private_key: CREDENTIALS.private_key,
  });

  await doc.loadInfo();

  // Index of the sheet
  let sheet = doc.sheetsByIndex[0];

  let rows = await sheet.getRows();

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    if (row[keyValue] === oldValue) {
      rows[index][keyValue] = newValue;
      await rows[index].save();
      break;
    }
  }
};

// updateRow('email', 'email@gmail.com', 'ramesh@ramesh.com')

const deleteRow = async (keyValue, thisValue) => {
  // use service account creds
  await doc.useServiceAccountAuth({
    client_email: CREDENTIALS.client_email,
    private_key: CREDENTIALS.private_key,
  });

  await doc.loadInfo();

  // Index of the sheet
  let sheet = doc.sheetsByIndex[0];

  let rows = await sheet.getRows();

  for (let index = 0; index < rows.length; index++) {
    const row = rows[index];
    if (row[keyValue] === thisValue) {
      await rows[index].delete();
      break;
    }
  }
};

// deleteRow("email", "ramesh@ramesh.com");
